version: '2'
services:
  web:
    image: rrcfesc/dockerfilesmagento2:5.6
    extra_hosts:
    - "course.local.com:127.0.0.1"
    expose:
    - "9000"
    ports:
    - "80:80"
    volumes:
    - ./src:/var/www/html
    - ~/.ssh:/home/magento/.ssh
    - ./apache_vhost:/etc/apache2/sites-available/
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.24.0.1
      PHP_IDE_CONFIG: "serverName=Backend"
    links:
    - mysql
    container_name: "multiplica_web"

  mysql:
    image: mysql:5.6
    volumes:
    - ./database/data:/var/lib/mysql
    ports:
    - 3308:3306
    environment:
    - MYSQL_ROOT_PASSWORD=hola123.
    container_name: "multiplica_db"
